# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Agent-facing Slack CLI for AI agents."
  homepage "https://github.com/howar31/slk"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/howar31/slk/releases/download/v0.8.0/slk_darwin_amd64.tar.gz"
      sha256 "259017533d1999271a7d5a52dc27b28c6a7529a11035cf0fd4a373be43187353"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/howar31/slk/releases/download/v0.8.0/slk_darwin_arm64.tar.gz"
      sha256 "8a36ab8ec5a6b64865186a9a245af83339933025a31423bc6c7f4f00d03ac067"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/howar31/slk/releases/download/v0.8.0/slk_linux_amd64.tar.gz"
      sha256 "1e560c9954f00581a26de36751578528928b12683aa3f31fbbef13d71053bf9e"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/howar31/slk/releases/download/v0.8.0/slk_linux_arm64.tar.gz"
      sha256 "4a30cbdc55f5983e4d5f56b79a2cdd892d020ff890314b1739438ef7eb16f97a"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slk --version")
  end
end
