# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Agent-facing Slack CLI for AI agents."
  homepage "https://github.com/howar31/slk"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/howar31/slk/releases/download/v0.6.0/slk_darwin_amd64.tar.gz"
      sha256 "60ec3695a396cc4bcc28edd4f8be421b1dd8aeed1786fad9d534aa7e35870477"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/howar31/slk/releases/download/v0.6.0/slk_darwin_arm64.tar.gz"
      sha256 "3f2c4d10f8f8d4bdc66cf352f82e117555c313a37c0336ccf9209bf979b3539e"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/howar31/slk/releases/download/v0.6.0/slk_linux_amd64.tar.gz"
      sha256 "2aaa359994dffda57822fea748245ae4be293e1ba2f5cc6212c56bde56518c82"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/howar31/slk/releases/download/v0.6.0/slk_linux_arm64.tar.gz"
      sha256 "cd6b74374cd11a0fbb10d5801ae58f3997741fec94179c711b103a0441e6b8f1"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slk --version")
  end
end
