# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Agent-facing Slack CLI for AI agents."
  homepage "https://github.com/howar31/slk"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/howar31/slk/releases/download/v0.2.0/slk_darwin_amd64.tar.gz"
      sha256 "01c6ce276ffcf322051dcadc6638384087403ec7b393e804c55169bb5271b222"

      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/howar31/slk/releases/download/v0.2.0/slk_darwin_arm64.tar.gz"
      sha256 "65a9f741c2fa320ec6c054be80ca0e0b78101540eef4904add027e832abdedd6"

      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/howar31/slk/releases/download/v0.2.0/slk_linux_amd64.tar.gz"
      sha256 "4365f4128c18ccf7055d76144151ab335332117fe73a3774ee305c88a4026d9e"
      define_method(:install) do
        bin.install "slk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/howar31/slk/releases/download/v0.2.0/slk_linux_arm64.tar.gz"
      sha256 "b4f6956a7086e6d1b10225344dfee370ca1f383c97837e1e23cf99ae266d9367"
      define_method(:install) do
        bin.install "slk"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slk --version")
  end
end
